# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Filter-SpamAssassin
version:      v0.0.1
version_from: lib/Email/Filter/SpamAssassin.pm
installdirs:  site
requires:
    Email::Filter:                 0
    Mail::SpamAssassin:            0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
